### ISSUE TITLE
Fail to export all recipes in xml or pdf

### ISSUE THREAD

**Issue by marillat** [GourmandRecipeManager/gourmand#119]
gourmand 1.0.0
Debian unstable amd64
Python 3.10.6

Export all recipes in. xml or. pdf fail with these errors
Export in html work.
```
emit error 1 Error during Exporter Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gourmand/threadManager.py", line 104, in run
    self.do_run()
  File "/usr/lib/python3/dist-packages/gourmand/plugin_loader.py", line 439, in _
    retval = f(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/gourmand/exporters/exporter.py", line 582, in do_run
    e.do_run()
  File "/usr/lib/python3/dist-packages/gourmand/exporters/exporter.py", line 88, in do_run
    self._write_text_()
  File "/usr/lib/python3/dist-packages/gourmand/plugin_loader.py", line 440, in _
    retval = self.run_post_hook(f.__name__,retval,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/gourmand/plugin_loader.py", line 400, in run_post_hook
    retval = hook(retval,self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/gourmand/plugin.py", line 200, in do_write
    val = field_fetcher(klass.r)
  File "/usr/lib/python3/dist-packages/gourmand/plugins/nutritional_information/export_plugin.py", line 26, in get_nutritional_info_as_text_blob
    nd = rd.nd
  File "/usr/lib/python3/dist-packages/gourmand/backends/db.py", line 1879, in __getattr__
    return getattr(self.rd, name)
AttributeError: 'RecData' object has no attribute 'nd'
```

**Comment by cydanil** [comment]
Thank you for reporting the issue.  
Could you possibly export that recipe in another format, such as the grmt format, and share it here?  

I'm lacking recipes with nutritional infos in the tests to catch this and troubleshoot it.  

Thanks!

**Comment by marillat** [comment]
How to export in grmt ?

**Comment by cydanil** [comment]
Perhaps you have a recipe that you feel comfortable sharing with nutritional information?   
I'm struggling to reproduce the issue with either of release 1.0.0 or the latest master.

**Comment by marillat** [comment]
I don't know why, but today I can export all recipes in xml with the same gourmand version.
