### ISSUE TITLE
launching gourmand fails with a crash with "TypeError: 'tuple' object does not support item assignment"

### ISSUE THREAD

**Issue by silverhikari** [GourmandRecipeManager/gourmand#134]
### Steps to Reproduce

1. build wheel from git version using python-build
2. install wheel into pipx with "pipx install ./"
3. try to launch gourmand
4. crash

### Expected Behavior
if the crash did not occur then the program should open displaying the recipes

### Current Behavior
fails with this error below
```
args = Namespace(db_url='', threads=False, gourmanddir='', thread_debug_interval=5.0, thread_debug=False, debug_file='', time=False, debug=None)
WARNING: Plugin module import failed
PATH: ['/home/silver/.local/pipx/venvs/gourmand/bin', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages', '/home/silver/.local/pipx/shared/lib/python3.10/site-packages', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export']
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 297, in get_module
    self._loaded = __import__(self.module)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/spellcheck/__init__.py", line 1, in <module>
    from . import reccard_spellcheck_plugin
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/spellcheck/reccard_spellcheck_plugin.py", line 4, in <module>
    from gtkspellcheck import SpellChecker
ModuleNotFoundError: No module named 'gtkspellcheck'
WARNING: Failed to load plugin spellcheck
ERROR:root:
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 126, in load_active_plugins
    self.active_plugins.extend(self.available_plugin_sets[p].plugins)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 309, in __getattr__
    return self.get_plugins()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 317, in get_plugins
    return self.get_module().plugins
AttributeError: 'NoneType' object has no attribute 'plugins'
Plugin  html_plugin not found
Plugin  archive_plugin not found
WARNING: Plugin module import failed
PATH: ['/home/silver/.local/pipx/venvs/gourmand/bin', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages', '/home/silver/.local/pipx/shared/lib/python3.10/site-packages', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export']
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 297, in get_module
    self._loaded = __import__(self.module)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export/pdf_plugin/__init__.py", line 1, in <module>
    from . import pdf_exporter_plugin, print_plugin
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export/pdf_plugin/pdf_exporter_plugin.py", line 4, in <module>
    from . import pdf_exporter
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export/pdf_plugin/pdf_exporter.py", line 8, in <module>
    from reportlab import platypus
ModuleNotFoundError: No module named 'reportlab'
WARNING: Failed to load plugin pdf_plugin
ERROR:root:
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 126, in load_active_plugins
    self.active_plugins.extend(self.available_plugin_sets[p].plugins)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 309, in __getattr__
    return self.get_plugins()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 317, in get_plugins
    return self.get_module().plugins
AttributeError: 'NoneType' object has no attribute 'plugins'
WARNING: Plugin module import failed
PATH: ['/home/silver/.local/pipx/venvs/gourmand/bin', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages', '/home/silver/.local/pipx/shared/lib/python3.10/site-packages', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins', '/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export']
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 297, in get_module
    self._loaded = __import__(self.module)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export/epub_plugin/__init__.py", line 1, in <module>
    from . import epub_exporter_plugin
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export/epub_plugin/epub_exporter_plugin.py", line 4, in <module>
    from . import epub_exporter
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugins/import_export/epub_plugin/epub_exporter.py", line 7, in <module>
    from ebooklib import epub
ModuleNotFoundError: No module named 'ebooklib'
WARNING: Failed to load plugin epub_plugin
ERROR:root:
Traceback (most recent call last):
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 126, in load_active_plugins
    self.active_plugins.extend(self.available_plugin_sets[p].plugins)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 309, in __getattr__
    return self.get_plugins()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/plugin_loader.py", line 317, in get_plugins
    return self.get_module().plugins
AttributeError: 'NoneType' object has no attribute 'plugins'
Traceback (most recent call last):
  File "/home/silver/.local/bin/gourmand", line 8, in <module>
    sys.exit(launch_app())
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/main.py", line 624, in launch_app
    RecGui.instance()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/main.py", line 848, in instance
    RecGui.__single = cls()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/main.py", line 863, in __init__
    RecIndex.__init__(self,
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/recindex.py", line 64, in __init__
    self.setup_widgets()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/recindex.py", line 139, in setup_widgets
    self.setup_search_views()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/recindex.py", line 210, in setup_search_views
    self.rvw: List['RowProxy'] = self.rd.search_recipes(self.searches,
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/backends/db.py", line 843, in search_recipes
    sort_by[i] = ('rating',d)
TypeError: 'tuple' object does not support item assignment
```

### Environment

* Operating System: Linux/Manjaro
* Version or commit id: last commit 928b6962e8dd49fe011b55eddf34d92324c29885
* Installed as Flatpak or Python package?: python, 3.10.8, pipx

i tryed a diffrent version of gourmand to see if maybe the recipe database got corrupted and was able to get it to load using the 1.0.0 appimage though trying to export the xml for backup failed. also tried launching with the second release canadite of 1.10 which had the same issue as above

**Comment by cydanil** [comment]
Thank you @silverhikari for taking the time to report the issue.  

A quick workaround, until a fix is published, is to either remove the `~/.local/share/gourmand/preferences.toml` file or editing it to remove the `[sort_by]` section in it.  
Deleting this file will remove your saved preferences, but will not affect your recipes.

I was able to reproduce it by first opening Gourmand, then changing a bunch of sorting options in the recipe list until toggling rating a few times in a row.  
It can also dupilcated by adding the following in `preferences.toml`:

```text
[sort_by]
column = "rating"
ascending = true
```

The fix is to convert the Tuple made when reading the preferences.toml to a list, probably in [`prefs.py`](https://github.com/GourmandRecipeManager/gourmand/blob/main/src/gourmand/prefs.py#L41) (or see of toml has an option to create lists rather than tuples).  

Cheers,
Cyril

**Comment by cydanil** [comment]
I was mistaken, the issue is at [`main.py:891](https://github.com/GourmandRecipeManager/gourmand/blob/main/src/gourmand/main.py#L891).  
I will make the fix and add tests.
