### ISSUE TITLE
Still an isssue with ingkey

### ISSUE THREAD

**Issue by marillat** [GourmandRecipeManager/gourmand#148]
Debian unstable amd64 python 3.11.2
When you try to modify an ingredient gourmand return the following error and nothing is modified.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 2375, in ingtree_edited_cb
    self.ingController.undoable_update_ingredient_row(ref,d)
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 1772, in undoable_update_ingredient_row
    ).perform()
      ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gourmand/Undo.py", line 77, in perform
    self.action(*self.action_args)
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 1768, in <lambda>
    lambda *args: self.update_ingredient_row(itr,**d),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: IngredientController.update_ingredient_row() got an unexpected keyword argument 'ingkey'
```

**Comment by marillat** [comment]
I noticed that this issue has been also reported in half fixed issue https://github.com/GourmandRecipeManager/gourmand/issues/141

**Comment by anonymous721** [comment]
I came here to report the same ingkey issues. Also on Debian.
I can enter ingredients only if there are no spaces in the ingredient, including quantities. So "butter" works, but "4 Tbsp butter" doesn't. Once "Butter" is in the list I can edit its entry to add the 4 and Tbsp to the appropriate columns, but trying to introduce a space to the ingredient name (e.g. changing to "clarified butter") again gives the ingkey error.

**Comment by marillat** [comment]
Tbsp don't seems to be a valid or a supported value in gourmand.

**Comment by anonymous721** [comment]
What do you mean? Tablespoons are a pretty essential unit, and all the recipes I already had (which were added back when it was Gourmet instead of Gourmand, before Debian updates changed me over) used Tbsp without trouble.

**Comment by FriedrichFroebel** [comment]
I am open to merging a corresponding PR.
