### ISSUE TITLE
Recipes can not be added as ingredients

### ISSUE THREAD

**Issue by Zimbelstern** [GourmandRecipeManager/gourmand#150]
*Debian bookworm with gourmand deb package 1.1.0+really1.1.0~rc3-3*

**I can not add a recipe as an ingredient.**

Steps to reproduce:
1. In the ingredient list click on `Add recipe`. The window `Choose recipe` opens.
2. Select a row and click on `OK`. A dialog opens:
`You haven't selected any recipes!`
3. Close the popup. An empty ingredient row is created and the following python error is thrown:
```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 2969, in response_cb
    self.ok()
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 2998, in ok
    self.ingEditor.ingtree_ui.ingController.add_ingredient_from_kwargs(
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 1752, in add_ingredient_from_kwargs
    self.update_ingredient_row(
TypeError: IngredientController.update_ingredient_row() got an unexpected keyword argument 'refid'
```

Instead of clicking on `OK` in step 2 you can double-click on a recipe. A dialog opens:
`How much of "My Recipe" does your recipe call for?` Click on `OK` and you will end up with the same `You haven't selected any recipes!` dialog.

**Comment by flochir** [comment]
Same here, proposed fix: #152
