### ISSUE TITLE
Fail to start with cannot import name '_ElementStringResult' from 'lxml.etree'

### ISSUE THREAD

**Issue by marillat** [GourmandRecipeManager/gourmand#163]
From Debian amd64 unstable python 3.11.9
```
$ gourmand 
args = Namespace(db_url='', threads=False, gourmanddir='', thread_debug_interval=5.0, thread_debug=False, debug_file='', time=False, debug=None)
Traceback (most recent call last):
  File "/usr/bin/gourmand", line 33, in <module>
    sys.exit(load_entry_point('gourmand==1.0.0', 'gui_scripts', 'gourmand')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/gourmand", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/gourmand/main.py", line 9, in <module>
    from gourmand import (__version__, batchEditor, convert, plugin, plugin_gui,
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 33, in <module>
    from gourmand.recindex import RecIndex
  File "/usr/lib/python3/dist-packages/gourmand/recindex.py", line 17, in <module>
    from .importers.clipboard_importer import import_from_drag_and_drop
  File "/usr/lib/python3/dist-packages/gourmand/importers/clipboard_importer.py", line 8, in <module>
    from gourmand.importers.importManager import ImportManager
  File "/usr/lib/python3/dist-packages/gourmand/importers/importManager.py", line 10, in <module>
    from gourmand.importers.web_importer import import_urls, supported_sites
  File "/usr/lib/python3/dist-packages/gourmand/importers/web_importer.py", line 6, in <module>
    from recipe_scrapers import SCRAPERS, scrape_me
  File "/usr/lib/python3/dist-packages/recipe_scrapers/__init__.py", line 6, in <module>
    from ._abstract import AbstractScraper
  File "/usr/lib/python3/dist-packages/recipe_scrapers/_abstract.py", line 13, in <module>
    from ._schemaorg import SchemaOrg
  File "/usr/lib/python3/dist-packages/recipe_scrapers/_schemaorg.py", line 8, in <module>
    import extruct
  File "/usr/lib/python3/dist-packages/extruct/__init__.py", line 1, in <module>
    from ._extruct import SYNTAXES, extract
  File "/usr/lib/python3/dist-packages/extruct/_extruct.py", line 9, in <module>
    from extruct.dublincore import DublinCoreExtractor
  File "/usr/lib/python3/dist-packages/extruct/dublincore.py", line 6, in <module>
    from extruct.utils import parse_html
  File "/usr/lib/python3/dist-packages/extruct/utils.py", line 5, in <module>
    from extruct.xmldom import XmlDomHTMLParser
  File "/usr/lib/python3/dist-packages/extruct/xmldom.py", line 9, in <module>
    from lxml.etree import (
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree' (/usr/lib/python3/dist-packages/lxml/etree.cpython-311-x86_64-linux-gnu.so)
```

**Comment by marillat** [comment]
The problem come from ```python3-extruct``` So closed.

**Comment by FriedrichFroebel** [comment]
This is an issue in `extruct` which has been fixed, but not yet released: https://github.com/scrapinghub/extruct/commit/9e0179be7721af29caab6bb29bd40e1a77f9ed2c
