### ISSUE TITLE
Errors trying to back up database on startup

### ISSUE THREAD

**Issue by seanms** [GourmandRecipeManager/gourmand#21]
gourmand wrongly thought it needed to upgrade the recipe database, then failed on the attempt.

### Steps to Reproduce

1.  Installed gourmand and copied the recipe database from gourmet v1.0.1.
2.  Ran gourmand a couple of times and made some minor edits.
3.  Restarted gourmand after the edits.

### Expected Behavior

Normal startup.

### Current Behavior

gourmand thought (incorrectly) that it needed to update the recipe database.  While attempting to create a backup before the upgrade, it failed with an exception.

Output follows:

```
Database older than 0.16.0 -- updating 0.11.0
Traceback (most recent call last):
  File "/app/bin/gourmand", line 8, in <module>
    sys.exit(launch_app())
  File "/app/lib/python3.8/site-packages/gourmand/main.py", line 617, in launch_app
    RecGui.instance()
  File "/app/lib/python3.8/site-packages/gourmand/main.py", line 837, in instance
    RecGui.__single = cls()
  File "/app/lib/python3.8/site-packages/gourmand/main.py", line 846, in __init__
    GourmandApplication.__init__(self)
  File "/app/lib/python3.8/site-packages/gourmand/main.py", line 69, in __init__
    self.setup_recipes() # Setup recipe database
  File "/app/lib/python3.8/site-packages/gourmand/main.py", line 146, in setup_recipes
    self.rd = recipeManager.default_rec_manager()
  File "/app/lib/python3.8/site-packages/gourmand/recipeManager.py", line 84, in default_rec_manager
    return get_recipe_manager(**dbargs)
  File "/app/lib/python3.8/site-packages/gourmand/recipeManager.py", line 81, in get_recipe_manager
    return RecipeManager.instance_for(**kwargs)
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 1861, in instance_for
    cls._instance_by_db_url[url] = cls(file, custom_url)
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 1867, in __init__
    self.rd = get_database(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 2144, in get_database
    return RecData.instance_for(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 152, in instance_for
    cls._instance_by_db_url[url] = cls(file, url)
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 175, in __init__
    self.update_version_info(gourmand.__version__.version)
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 504, in update_version_info
    self.backup_db()
  File "/app/lib/python3.8/site-packages/gourmand/backends/db.py", line 452, in backup_db
    backup_file_name = self.filename + '.backup-' + time.strftime('%d-%m-%y')
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```

### Possible Solution

The fix for the exception is:

```
--- db.py.ORIG	1969-12-31 16:00:00.000000000 -0800
+++ db.py	2021-08-21 14:16:59.539531843 -0700
@@ -449,7 +449,7 @@
     def backup_db(self):
         """Make a backup copy of the DB -- this ensures experimental
         code won't permanently screw our users."""
-        backup_file_name = self.filename + '.backup-' + time.strftime('%d-%m-%y')
+        backup_file_name = str(self.filename) + '.backup-' + time.strftime('%d-%m-%y')
         while os.path.exists(backup_file_name):
             backup_file_name += 'I'
         print(f'Making a backup copy of DB to {backup_file_name}')
```

### Environment

* Operating System:  Fedora 33
* Version or commit id:  1.0.0
* Installed as Flatpak or Python package?:  flatpak

**Comment by cydanil** [comment]
Thank you for reporting the issue and taking time to investigate it!  

I've made a fix, and it will be in the next version :)
