### ISSUE TITLE
Error "libffi.so.7: cannot open shared object file" when running on a clean installation

### ISSUE THREAD

**Issue by jdglanville** [GourmandRecipeManager/gourmand#41]
### Steps to Reproduce
1. Pulled the 1.0.0 build from releases, specifically `Gourmand-1.0.0-x86_64.AppImage`
2. Set the execute bit: `chmod +x Gourmand-1.0.0-x86_64.AppImage`
3. Ran gourmand: `./Gourmand-1.0.0-x86_64.AppImage`
4. application produced a stack trace.

### Expected Behavior
The application should start.

### Current Behavior
Received the following stack trace:
```
Traceback (most recent call last):
  File "/tmp/.mount_GourmaYjXBgr/usr/bin/gourmand", line 6, in <module>
    from gourmand.main import launch_app
  File "/tmp/.mount_GourmaYjXBgr/opt/python3.8/lib/python3.8/site-packages/gourmand/__init__.py", line 1, in <module>
    from gi import require_version
  File "/tmp/.mount_GourmaYjXBgr/opt/python3.8/lib/python3.8/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

### Possible Solution
Unknown

### Environment
* Operating System: Ubuntu 21.04, 64-bit
* Version or commit id: Using release 1.0.0 ([link to release](https://github.com/GourmandRecipeManager/gourmand/releases/tag/1.0.0)).
* Installed as Flatpak or Python package?: Using the AppImage package

**Comment by cydanil** [comment]
Thanks for reporting the issue! 
I think the solution is to package libffi within the appimage.

Meanwhile, there's an [ugly hack to work around this](https://github.com/kirienko/gourmet/issues/329#issuecomment-861920894) which requires copying libffi,  but only do it if you feel comfortable.

**Comment by cydanil** [comment]
I think I know how to include the library, but I need more time to test the solution on different platforms.  
Thanks for specifying which distribution you use: it will make testing easier :)

**Comment by cydanil** [comment]
I resolved the issue by packaging libffi 7 within the AppImage, as Ubuntu 20.10 uses libffi 8.  
I successfully created an AppImage using the CI and ran it with no further work on Ubuntu 20.10:  

![image](https://user-images.githubusercontent.com/2159577/136187189-d9481198-341b-4561-a2f3-34fed50f8fc5.png)


The AppImage I used for testing will be [available here](https://github.com/GourmandRecipeManager/gourmand/actions/runs/1311472974) for some time, but keep in mind that it's the development version, and not a proper release.
