### ISSUE TITLE
Trying to open trash gives traceback.

### ISSUE THREAD

**Issue by eliotb** [GourmandRecipeManager/gourmand#57]
### Steps to Reproduce

1. Click Tools/Open Trash

### Current Behavior
```Traceback (most recent call last):
  File "/home/eliot/src/python/gourmand/src/gourmand/main.py", line 1260, in _on_bar_response
    self.show_deleted_recs()
  File "/home/eliot/src/python/gourmand/src/gourmand/main.py", line 1136, in show_deleted_recs
    self.recTrash = RecTrash(self.rg)
  File "/home/eliot/src/python/gourmand/src/gourmand/main.py", line 476, in __init__
    RecIndex.__init__(self, self.ui, self.rg.rd, self.rg)
  File "/home/eliot/src/python/gourmand/src/gourmand/recindex.py", line 63, in __init__
    self.setup_widgets()
  File "/home/eliot/src/python/gourmand/src/gourmand/recindex.py", line 138, in setup_widgets
    self.setup_search_views()
  File "/home/eliot/src/python/gourmand/src/gourmand/recindex.py", line 210, in setup_search_views
    sort_by=self.sort_by)
AttributeError: 'RecTrash' object has no attribute 'sort_by'
```

### Environment

* Operating System: Linux ubuntu 20.04
* Version or commit id: 989faf26858a5ce4f5f4770a23e1c1154ecbbd16 
* Git checkout.

**Comment by cydanil** [comment]
Thank you!  
I had introduced this problem when saving the index sort order in the main window.
This is now resolved :)
