### ISSUE TITLE
 Conversion of gourmet recipes to gourmand failed: servings/yields

### ISSUE THREAD

**Issue by marillat** [GourmandRecipeManager/gourmand#96]
Hi,

This is a Debian bug report https://bugs.debian.org/1009098

```
A number of my recipes crash when loading:

DEBUG:   /usr/lib/python3/dist-packages/gourmand/reccard.py: 481 showing attribute rating = 2                                                                                                                   4:27am
DEBUG:   /usr/lib/python3/dist-packages/gourmand/reccard.py: 495 hiding attribute preptime
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gourmand/main.py", line 1083, in show
    w = reccard.RecCard(self, rec)
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 72, in __init__
    self.show()
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 117, in show
    self.show_display()
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 97, in show_display
    self.__rec_display = RecCardDisplay(self, self.__rec_gui,
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 201, in __init__
    self.update_from_database()
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 470, in update_from_database
    special_display_functions[attr]()
  File "/usr/lib/python3/dist-packages/gourmand/reccard.py", line 517, in update_yields_display
    self.yields_orig = float(self.yields_orig)
TypeError: float() argument must be a string or a number, not 'NoneType'

I believe it is because the yields is null.  If I run sqlite3 on the gourmet database, both yields and servings were set to 0.0.
In gourmand, both the yields and servings were set to null.  

Running: update recipe set yields=0 where yields is null;
fixes the problem.
```

**Comment by cydanil** [comment]
Thanks @marillat for forwarding me the issue!  
This was resolved in https://github.com/GourmandRecipeManager/gourmand/commit/0ac9c0b9e8b929ae2c9d211d4d7fbef2c9dca319, which will be in the next release :)

**Comment by marillat** [comment]
Thanks for the patch. Applied to the Debian package.
